import 'package:get/get.dart';

class LocalizationString extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'title': 'LandSlide Report',
      'tool': 'tool',
      'settings': 'Settings',
      'dashboard': 'Dashboard',
      'change_password': 'Change Password',
      'help_center': 'Help Center',
      'faq': 'FAQ',
      'profile_title': 'Profile',
      'profile_info': 'Profile Info',
      'profile_info_name': 'Full Name',
      'profile_info_email': 'Email Address',
      'profile_info_address': 'Address',
      'profile_info_update_button': 'Update Profile Info',
      'profile_language_select': 'Select Language',
      'profile_logout': 'Logout',
      'profile_logout_text': 'Logging out? We will be here when you are back!',
      'dashboard_sidebar_important_video': 'App Manual',
      'dashboard_sidebar_about_us': 'About Us',
      'dashboard_sidebar_privacy_policy': 'Privacy Policy',
      'dashboard_rainfall': 'Rainfall',
      'dashboard_humidity': 'Humidity',
      'dashboard_wind': 'Wind Speed',
      'dashboard_time_good_morning': "Good Morning",
      'dashboard_time_good_noon': "Good Noon",
      'dashboard_time_good_afternoon': "Good Afternoon",
      'dashboard_time_good_evening': "Good Evening",
      'dashboard_time_good_night': "Good Night",
      'dashboard_weather_forecast': 'Weather\nForecast',
      'dashboard_weather_alert': 'Weather\nAlert',
      'dashboard_flood_forecast': 'Flood\nForecast',
      'dashboard_crop_advisory': 'Crop\nAdvisory',
      'dashboard_pest_disease': 'Disease\nAlert',
      'dashboard_pest_disease_information': 'Disease\nInformation',
      'dashboard_task_reminder': 'Task\nReminder',
      'dashboard_advisory_bulletin': 'Advisory\nBulletin',
      'community_connection': 'Community\nConnection',
      'weather_forecast': 'Weather Forecast',
      'wf_title': 'Weather Forecast',
      'wf_subtitle': 'Weather forecast for next 10 days',
      'wf_temp': 'Temparature',
      'wf_rf': 'Rainfall',
      'wf_rh': 'Humidity',
      'wf_wind': 'Wind Speed',
    },
    'bn_BD': {
      'title': 'LandSlide Report',
      'tool': 'tool',
      'settings': 'সেটিংস',
      'dashboard': 'ড্যাশবোর্ড',
      'change_password': 'পাসওয়ার্ড পরিবর্তন করুন',
      'help_center': 'সাহায্য কেন্দ্র',
      'faq': 'জিজ্ঞাসিত প্রশ্নাবলী',
      'profile_title': 'প্রোফাইল',
      'profile_info': 'প্রোফাইল বিত্রান্ত',
      'profile_info_name': 'পুরো নাম',
      'profile_info_email': 'ইমেল এড্রেস',
      'profile_info_address': 'ঠিকানা',
      'profile_info_update_button': 'প্রোফাইল ইনফো হালনাগাদ করুণ',
      'profile_language_select': 'ভাষা নির্বাচন করুণ',
      'profile_logout': 'লগ আউট',
      'profile_logout_text': 'তুমি কী প্রস্থান করতে চাও? আমাদের আবার দেখা হবে তুমি যখন ফিরে আসবে।',
      'dashboard_sidebar_important_video': 'অ্যাপ ম্যানুয়াল',
      'dashboard_sidebar_about_us': 'আমাদের সম্পর্কে',
      'dashboard_sidebar_privacy_policy': 'গোপনীয়তা নীতি',
      'dashboard_rainfall': 'বৃষ্টিপাত',
      'dashboard_humidity': 'আর্দ্রতা',
      'dashboard_wind': 'বাতাসের গতি',
      'dashboard_time_good_morning': "শুভ সকাল",
      'dashboard_time_good_noon': "শুভ দুপুর",
      'dashboard_time_good_afternoon': "শুভ বিকাল",
      'dashboard_time_good_evening': "শুভ সন্ধা",
      'dashboard_time_good_night': "শুভ রাত্রি",
      'dashboard_weather_forecast': 'আবহাওয়া\nপূর্বাভাস',
      'dashboard_weather_alert': 'আবহাওয়া\nসতর্কবার্তা',
      'dashboard_flood_forecast': 'বন্যা\nপূর্বাভাস',
      'dashboard_crop_advisory': 'ফসল\nপরামর্শ',
      'dashboard_pest_disease': 'রোগের\nসতর্কতা',
      'dashboard_pest_disease_information': 'রোগের\nতথ্য',
      'dashboard_task_reminder': 'টাস্ক\nরিমাইন্ডার',
      'dashboard_advisory_bulletin': 'এডভাইজারি\nবুলেটিন',
      'community_connection': 'জনসাধারণ\nসংযোগ',
      'weather_forecast': 'আবহাওয়া পূর্বাভাস',
      'wf_title': 'আবহাওয়া পূর্বাভাস',
      'wf_subtitle': 'পরবর্তী ১০ দিনের আবহাওয়া পূর্বাভাস',
      'wf_temp': 'তাপমাত্রা',
      'wf_rf': 'বৃষ্টিপাত',
      'wf_rh': 'আপেক্ষিক আর্দ্রতা',
      'wf_wind': 'বাতাসের গতি',
    }
  };
}